config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get '/article/:slug', to: 'articles#show', as: 'article'
  get '/editor', to: 'articles#new'
  get '/editor/:slug', to: 'articles#edit', as: 'edit_article'
  get '/register', to: 'users#new'
  get '/profile/:username', to: 'users#show', as: 'profile'
  get '/settings', to: 'users#edit'
  get '/login', to: 'sessions#new'

  post '/api/articles', to: 'articles#create', as: 'post_article'
  patch '/api/articles/:slug', to: 'articles#update', as: 'patch_article'
  delete '/api/articles/:slug', to: 'articles#destroy', as: 'delete_article'
  post '/api/articles/:slug/comments', to: 'comments#create', as: 'post_comment'
  delete '/api/articles/:slug/comments/:id', to: 'comments#destroy', as: 'delete_comment'
  post '/api/users', to: 'users#create'
  patch '/api/user', to: 'users#update'
  post   '/api/users/login',   to: 'sessions#create'
  delete '/api/users/logout',  to: 'sessions#destroy'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  before_validation :generate_slug, on: :create

  validates :title, presence: true, length: { maximum: 32 }
  validates :slug, presence: true
  validates :description, presence: true, length: { maximum: 128 }
  validates :body, presence: true, length: { maximum: 512 }
  validates :user_id, presence: true

  private

  def generate_slug
    slug_base = title ? title.parameterize : ''
    self.slug = "#{slug_base}-#{Time.now.to_i}"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in_user, only: %i[new edit create update destroy]
  before_action :correct_user,   only: %i[edit update destroy]

  def index
    @articles = Article.page(params[:page])
    @tags = Tag.limit(10)
  end

  def show
    @article = Article.find_by(slug: params[:slug])
    @comments = @article.comments
  end

  def new
    @article = current_user.articles.build if logged_in?
  end

  def edit
    @article = Article.find_by(slug: params[:slug])
  end

  def create
    @article = current_user.articles.build(article_params)
    tag_list = params[:article][:tag_list]
    if @article.save
      if tag_list.present?
        tags = tag_list.split(',').map(&:strip).uniq
        create_or_update_article_tags(@article, tags)
      end
      flash[:success] = 'Article posted'
      redirect_to article_url(@article.slug)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    tag_list = params[:article][:tag_list]
    if @article.update(article_params)
      if tag_list.present?
        tags = tag_list.split(',').map(&:strip).uniq
        create_or_update_article_tags(@article, tags)
      end
      flash[:success] = 'Article updated'
      redirect_to article_url(@article.slug)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    flash[:success] = 'Article deleted'
    if request.referrer.nil?
      redirect_to root_url, status: :see_other
    else
      redirect_to request.referrer, status: :see_other
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, :body)
  end

  def correct_user
    @article = current_user.articles.find_by(slug: params[:slug])
    redirect_to root_url, status: :see_other if @article.nil?
  end

  def create_or_update_article_tags(article, tags)
    article.tags.destroy_all

    tags.each do |tag|
      tag = Tag.find_or_create_by(name: tag)
      article.tags << tag
    rescue ActiveRecord::RecordInvalid
      false
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="article-preview">
  <div class="article-meta">
    <%= link_to profile_path(article.user.username) do %>
      <img src="<%= article.user.image %>" />
    <% end %>
    <div class="info">
      <%= link_to article.user.username, profile_path(article.user.username), class: 'author' %>
      <span class="date"><%= article.created_at.strftime('%B %d, %Y') %></span>
    </div>
  </div>
  <%= link_to article_path(article.slug), class: 'preview-link' do %>
    <h1><%= article.title %></h1>
    <p><%= article.description %></p>
    <span>Read more...</span>
    <ul class="tag-list">
      <% article.tags.each do |tag| %>
        <li class="tag-default tag-pill tag-outline"><%= tag.name %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/articles/_article_meta.html.erb
<div class="article-meta">
  <a href="/profile/<%= @article.user.username %>"><img src="<%= @article.user.image %>" /></a>
  <div class="info">
    <a href="/profile/<%= @article.user.username %>" class="author"><%= @article.user.username %></a>
    <span class="date"><%= @article.created_at.strftime('%B %-d, %Y') %></span>
  </div>
  <% if logged_in? %>
    <% unless current_user?(@article.user) %>
      <button class="btn btn-sm btn-outline-secondary">
        <i class="ion-plus-round"></i>
        &nbsp; Follow <%= @article.user.username %>
      </button>
      &nbsp;
    <% end %>
    <% if current_user?(@article.user) %>
      <%= link_to edit_article_path(@article.slug), class: 'btn btn-sm btn-outline-secondary' do %>
        <i class="ion-edit"></i>&nbsp;Edit Article
      <% end %>
      <%= link_to delete_article_path(@article.slug), class: 'btn btn-sm btn-outline-danger', data: { "turbo-method": :delete,
                                               turbo_confirm: "You sure?" } do %>
        <i class="ion-trash-a"></i> Delete Article
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/articles/_comment.html.erb
<div class="card">
  <div class="card-block">
    <p class="card-text">
      <%= comment.body %>
    </p>
  </div>
  <div class="card-footer">
    <a href="/profile/author" class="comment-author">
      <%= link_to profile_path(comment.user.username), class: 'comment-author' do %>
        <img src="<%= comment.user.image %>" class="comment-author-img" />
      <% end %>
      &nbsp;
      <%= link_to comment.user.username, profile_path(comment.user.username), class: 'comment-author' %>
      <span class="date-posted"><%= comment.created_at.strftime('%B %-d, %Y') %></span>
      <% if current_user?(comment.user) %>
        <%= link_to delete_comment_path(@article.slug, comment.id), class: 'btn btn-sm btn-outline-danger', data: { "turbo-method": :delete,
                                               turbo_confirm: "You sure?" } do %>
          <i class="ion-trash-a"></i> Delete Comment
        <% end %>
      <%end%>
    </div>
  </div>

app/views/articles/article.html.erb
<% provide(:title, "Article") %>
<div class="article-page">
  <div class="banner">
    <div class="container">
      <h1><%= @article.title %></h1>
      <div class="article-meta">
        <a href="/profile/eric-simons"><img src="http://i.imgur.com/Qr71crq.jpg" /></a>
        <div class="info">
          <a href="/profile/eric-simons" class="author">Eric Simons</a>
          <span class="date">January 20th</span>
        </div>
        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-plus-round"></i>
          &nbsp; Follow Eric Simons <span class="counter">(10)</span>
        </button>
        &nbsp;&nbsp;
        <button class="btn btn-sm btn-outline-primary">
          <i class="ion-heart"></i>
          &nbsp; Favorite Post <span class="counter">(29)</span>
        </button>
        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-edit"></i> Edit Article
        </button>
        <button class="btn btn-sm btn-outline-danger">
          <i class="ion-trash-a"></i> Delete Article
        </button>
      </div>
    </div>
  </div>
  <div class="container page">
    <div class="row article-content">
      <div class="col-md-12">
        <p><%= @article.body %></p>
        <ul class="tag-list">
          <% @article.tags.each do |tag| %>
            <li class="tag-default tag-pill tag-outline"><%= tag.name %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <hr />
    <div class="article-actions">
      <div class="article-meta">
        <a href="profile.html"><img src="http://i.imgur.com/Qr71crq.jpg" /></a>
        <div class="info">
          <a href="" class="author">Eric Simons</a>
          <span class="date">January 20th</span>
        </div>
        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-plus-round"></i>
          &nbsp; Follow Eric Simons
        </button>
        &nbsp;
        <button class="btn btn-sm btn-outline-primary">
          <i class="ion-heart"></i>
          &nbsp; Favorite Article <span class="counter">(29)</span>
        </button>
        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-edit"></i> Edit Article
        </button>
        <button class="btn btn-sm btn-outline-danger">
          <i class="ion-trash-a"></i> Delete Article
        </button>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-8 offset-md-2">
        <form class="card comment-form">
          <div class="card-block">
            <textarea class="form-control" placeholder="Write a comment..." rows="3"></textarea>
          </div>
          <div class="card-footer">
            <img src="http://i.imgur.com/Qr71crq.jpg" class="comment-author-img" />
            <button class="btn btn-sm btn-primary">Post Comment</button>
          </div>
        </form>
        <div class="card">
          <div class="card-block">
            <p class="card-text">
              With supporting text below as a natural lead-in to additional content.
            </p>
          </div>
          <div class="card-footer">
            <a href="/profile/author" class="comment-author">
              <img src="http://i.imgur.com/Qr71crq.jpg" class="comment-author-img" />
            </a>
            &nbsp;
            <a href="/profile/jacob-schmidt" class="comment-author">Jacob Schmidt</a>
            <span class="date-posted">Dec 29th</span>
          </div>
        </div>
        <div class="card">
          <div class="card-block">
            <p class="card-text">
              With supporting text below as a natural lead-in to additional content.
            </p>
          </div>
          <div class="card-footer">
            <a href="/profile/author" class="comment-author">
              <img src="http://i.imgur.com/Qr71crq.jpg" class="comment-author-img" />
            </a>
            &nbsp;
            <a href="/profile/jacob-schmidt" class="comment-author">Jacob Schmidt</a>
            <span class="date-posted">Dec 29th</span>
            <span class="mod-options">
              <i class="ion-trash-a"></i>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<% provide(:title, "Edit") %>
<div class="editor-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-10 offset-md-1 col-xs-12">
        <%= render 'shared/article_form' %>
      </div>
    </div>
  </div>
</div>

app/views/articles/home.html.erb
<% provide(:title, "Home") %>
<div class="home-page">
  <div class="banner">
    <div class="container">
      <h1 class="logo-font">conduit</h1>
      <p>A place to share your knowledge.</p>
    </div>
  </div>
  <div class="container page">
    <div class="row">
      <div class="col-md-9">
        <div class="feed-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a class="nav-link" href="">Your Feed</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="">Global Feed</a>
            </li>
          </ul>
        </div>
        <% @articles.each do |article| %>
          <div class="article-preview">
            <div class="article-meta">
              <a href="/profile/eric-simons"><img src="https://i.imgur.com/Qr71crq.jpeg" /></a>
              <div class="info">
                <a href="/profile/eric-simons" class="author">Eric Simons</a>
                <span class="date">January 20th</span>
              </div>
              <button class="btn btn-outline-primary btn-sm pull-xs-right">
                <i class="ion-heart"></i> 29
              </button>
            </div>
            <a href="/article/<%= article.slug %>" class="preview-link">
              <h1><%= article.title %></h1>
              <p><%= article.description %></p>
              <span>Read more...</span>
              <ul class="tag-list">
                <% article.tags.each do |tag| %>
                  <li class="tag-default tag-pill tag-outline"><%= tag.name %></li>
                <% end %>
              </ul>
            </a>
          </div>
        <% end %>
        <ul class="pagination">
          <li class="page-item active">
            <a class="page-link" href="">1</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="">2</a>
          </li>
        </ul>
      </div>
      <div class="col-md-3">
        <div class="sidebar">
          <p>Popular Tags</p>
          <div class="tag-list">
            <% @tags.each do |tag| %>
              <a href="" class="tag-pill tag-default"><%= tag.name %></a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<% provide(:title, "Home") %>
<div class="home-page">
  <div class="banner">
    <div class="container">
      <h1 class="logo-font">conduit</h1>
      <p>A place to share your knowledge.</p>
    </div>
  </div>
  <div class="container page">
    <div class="row">
      <div class="col-md-9">
        <div class="feed-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a class="nav-link" href="">Your Feed</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="">Global Feed</a>
            </li>
          </ul>
        </div>
        <%= render @articles %>
        <%= paginate @articles %>
      </div>
      <div class="col-md-3">
        <div class="sidebar">
          <p>Popular Tags</p>
          <div class="tag-list">
            <% @tags.each do |tag| %>
              <a href="" class="tag-pill tag-default"><%= tag.name %></a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<% provide(:title, "Editor") %>
<div class="editor-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-10 offset-md-1 col-xs-12">
        <%= form_with(model: @article, url: api_articles_path) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>

          <%= f.label :description %>
          <%= f.text_field :description, class: 'form-control' %>

          <%= f.label :body %>
          <%= f.text_field :body, class: 'form-control' %>

          <%= f.submit "Publish Article", class: "btn btn-lg pull-xs-right btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<% provide(:title, "Article") %>
<div class="article-page">
  <div class="banner">
    <div class="container">
      <h1><%= @article.title %></h1>
      <%= render "articles/article_meta" %>
    </div>
  </div>
  <div class="container page">
    <div class="row article-content">
      <div class="col-md-12">
        <p><%= @article.body %></p>
        <ul class="tag-list">
          <% @article.tags.each do |tag| %>
            <li class="tag-default tag-pill tag-outline"><%= tag.name %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <hr />
    <div class="article-actions">
      <%= render "articles/article_meta" %>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-8 offset-md-2">
        <% if logged_in? %>
          <%= form_with(model: @comment, url: post_comment_path(@article.slug), class: 'card comment-form', local: true) do |f| %>
            <div class="card-block">
              <%= f.text_area :body, class: 'form-control', rows: 3, placeholder: "Write a comment..." %>
            </div>
            <div class="card-footer">
              <img src="<%= current_user.image %>" class="comment-author-img" />
              <%= f.submit "Post Comment", class: "btn btn-sm btn-primary" %>
            </div>
          <% end %>
        <% end %>
        <%= render partial: 'articles/comment', collection: @comments %>
      </div>
    </div>
  </div>
</div>