config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get '/article/:slug', to: 'articles#show', as: 'article'
  get '/editor', to: 'articles#new'
  get '/editor/:slug', to: 'articles#edit', as: 'edit_article'
  get '/register', to: 'users#new'
  get '/profile/:username', to: 'users#show', as: 'profile'
  get '/settings', to: 'users#edit'
  get '/login', to: 'sessions#new'

  post '/api/articles', to: 'articles#create', as: 'post_article'
  patch '/api/articles/:slug', to: 'articles#update', as: 'patch_article'
  delete '/api/articles/:slug', to: 'articles#destroy', as: 'delete_article'
  post '/api/articles/:slug/comments', to: 'comments#create', as: 'post_comment'
  delete '/api/articles/:slug/comments/:id', to: 'comments#destroy', as: 'delete_comment'
  post '/api/users', to: 'users#create'
  patch '/api/user', to: 'users#update'
  post   '/api/users/login',   to: 'sessions#create'
  delete '/api/users/logout',  to: 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { maximum: 50 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d-]+(\.[a-z\d-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  def feed
    Article.where('user_id = ?', id)
  end

  # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost:)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[edit update]

  def show
    @user = User.find_by(username: params[:username])
    @feed_items = @user.feed.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = 'Welcome to Conduit Clone!'
      redirect_to profile_url(@user.username)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_edit_params)
      flash[:success] = 'Profile updated'
      redirect_to profile_url(@user.username)
    else
      @user.reload
      render 'edit', status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def user_edit_params
    params.require(:user).permit(:username, :email, :image, :bio, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<div class="settings-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-6 offset-md-3 col-xs-12">
        <h1 class="text-xs-center">Your Settings</h1>
        <%= form_with(model: @user, url: api_user_path) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <fieldset>
            <fieldset class="form-group">
              <%= f.text_field :image, class: 'form-control', placeholder: 'URL of profile picture' %>
            </fieldset>
            <fieldset class="form-group">
              <%= f.text_field :username, class: 'form-control form-control-lg', placeholder: 'Your Name' %>
            </fieldset>
            <fieldset class="form-group">
              <%= f.text_area :bio, class: 'form-control form-control-lg', rows: 8, placeholder: 'Short bio about you' %>
            </fieldset>
            <fieldset class="form-group">
              <%= f.email_field :email, class: 'form-control form-control-lg', placeholder: 'Email' %>
            </fieldset>
            <fieldset class="form-group">
              <%= f.password_field :password, class: 'form-control form-control-lg', placeholder: 'New Password' %>
            </fieldset>
            <%= f.submit "Update Settings", class: "btn btn-lg btn-primary pull-xs-right" %>
          </fieldset>
        <% end %>
        <hr />
        <%= link_to api_users_logout_path, data: { "turbo-method": :delete }, class: 'btn btn-outline-danger' do %>
          Or click here to logout.
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="auth-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-6 offset-md-3 col-xs-12">
        <h1 class="text-xs-center">Sign up</h1>
        <p class="text-xs-center">
          <a href="/login">Have an account?</a>
        </p>
        <%= form_with(model: @user, url: api_users_path) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <fieldset class="form-group">
            <%= f.text_field :username, class: 'form-control form-control-lg', placeholder: 'Username' %>
          </fieldset>
          <fieldset class="form-group">
            <%= f.email_field :email, class: 'form-control form-control-lg', placeholder: 'Email'  %>
          </fieldset>
          <fieldset class="form-group">
            <%= f.password_field :password, class: 'form-control form-control-lg', placeholder: 'Password'  %>
          </fieldset>
          <%= f.submit "Sign up", class: "btn btn-lg btn-primary pull-xs-right" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="profile-page">
  <div class="user-info">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-10 offset-md-1">
          <% if @user.image %>
            <img src="<%= @user.image %>" class="user-img" />
          <% else %>
            <img src="http://i.imgur.com/Qr71crq.jpg" class="user-img" />
          <% end %>
          <h4><%= @user.username %></h4>
          <p>
            <%= @user.bio %>
          </p>
          <% if current_user?(@user) %>
            <%= link_to settings_path, class: 'btn btn-sm btn-outline-secondary action-btn' do %>
              <i class="ion-gear-a"></i>
              &nbsp; Edit Profile Settings
            <% end %>
          <% elsif logged_in? %>
            <button class="btn btn-sm btn-outline-secondary action-btn">
              <i class="ion-plus-round"></i>
              &nbsp; Follow <%= @user.username %>
            </button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-10 offset-md-1">
        <div class="articles-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a class="nav-link active" href="">My Articles</a>
            </li>
          </ul>
        </div>
        <%= render "shared/feed" %>
      </div>
    </div>
  </div>
</div>