config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get '/article/:slug', to: 'articles#show', as: 'article'
  get '/editor', to: 'articles#new'
  get '/editor/:slug', to: 'articles#edit', as: 'edit_article'
  get '/register', to: 'users#new'
  get '/profile/:username', to: 'users#show', as: 'profile'
  get '/settings', to: 'users#edit'
  get '/login', to: 'sessions#new'

  post '/api/articles', to: 'articles#create', as: 'post_article'
  patch '/api/articles/:slug', to: 'articles#update', as: 'patch_article'
  delete '/api/articles/:slug', to: 'articles#destroy', as: 'delete_article'
  post '/api/articles/:slug/comments', to: 'comments#create', as: 'post_comment'
  delete '/api/articles/:slug/comments/:id', to: 'comments#destroy', as: 'delete_comment'
  post '/api/users', to: 'users#create'
  patch '/api/user', to: 'users#update'
  post   '/api/users/login',   to: 'sessions#create'
  delete '/api/users/logout',  to: 'sessions#destroy'
end

app/views/shared/_article_form.html.erb
<%= javascript_import_module_tag "custom/tagging" %>
<% if ['new', 'create'].include?(action_name) %>
  <% url = post_article_path %>
<% elsif action_name == 'edit' %>
  <% url = patch_article_path %>
<% end %>
<%= form_with(model: @article, url: url, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <fieldset>
    <fieldset class="form-group">
      <%= f.text_field :title, class: 'form-control', placeholder: 'Article Title' %>
    </fieldset>
    <fieldset class="form-group">
      <%= f.text_field :description, class: 'form-control', placeholder: "What's this article about?" %>
    </fieldset>
    <fieldset class="form-group">
      <%= f.text_area :body, class: 'form-control', rows: "8", placeholder: "Write your article (in markdown)" %>
    </fieldset>
    <fieldset class="form-group">
      <%= f.text_field :tags, value: nil, class: 'form-control', placeholder: "Enter tags" %>
    </fieldset>
    <%= f.hidden_field :tag_list, value: @article.tags.map(&:name), id: 'hidden-tag-list' %>
    <div id="tag-list" class="tag-list">
    </div>
    <%= f.submit "Publish Article", class: "btn btn-lg pull-xs-right btn-primary" %>
  </fieldset>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul class="error-messages">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <%= render @feed_items %>
  <%= paginate @feed_items %>
<% end %>