config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get '/article/:slug', to: 'articles#show', as: 'article'
  get '/editor', to: 'articles#new'
  get '/editor/:slug', to: 'articles#edit', as: 'edit_article'
  get '/register', to: 'users#new'
  get '/profile/:username', to: 'users#show', as: 'profile'
  get '/settings', to: 'users#edit'
  get '/login', to: 'sessions#new'

  post '/api/articles', to: 'articles#create', as: 'post_article'
  patch '/api/articles/:slug', to: 'articles#update', as: 'patch_article'
  delete '/api/articles/:slug', to: 'articles#destroy', as: 'delete_article'
  post '/api/articles/:slug/comments', to: 'comments#create', as: 'post_comment'
  delete '/api/articles/:slug/comments/:id', to: 'comments#destroy', as: 'delete_comment'
  post '/api/users', to: 'users#create'
  patch '/api/user', to: 'users#update'
  post   '/api/users/login',   to: 'sessions#create'
  delete '/api/users/logout',  to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <a href="/" class="logo-font">conduit</a>
    <span class="attribution">
      An interactive learning project from <a href="https://thinkster.io">Thinkster</a>. Code &amp;
      design licensed under MIT.
    </span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light">
  <div class="container">
    <a class="navbar-brand" href="/">conduit</a>
    <ul class="nav navbar-nav pull-xs-right">
      <li class="nav-item">
        <!-- Add "active" class when you're on that page" -->
        <a class="nav-link active" href="/">Home</a>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to '/editor', class: 'nav-link' do %>
            <i class="ion-compose"></i>&nbsp;New Article
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to '/settings', class: 'nav-link' do %>
            <i class="ion-gear-a"></i>&nbsp;Settings
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to profile_path(current_user.username), class: 'nav-link' do %>
            <img src="<%= current_user.image %>" class="user-pic" />
            <%= current_user.username %>
          <% end %>
        </li>
      <% else%>
        <li class="nav-item">
          <%= link_to "Sign in", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", register_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <meta name="referrer" content="no-referrer">
    <%= stylesheet_link_tag "//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" %>
    <%= stylesheet_link_tag "//fonts.googleapis.com/css?family=Titillium+Web:700|Source+Serif+Pro:400,700|Merriweather+Sans:400,700|Source+Sans+Pro:400,300,600,700,300italic,400italic,600italic,700italic" %>
    <%= stylesheet_link_tag "//demo.productionready.io/main.css" %>
    <%= render 'layouts/rails_default' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>